export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";

export const REQUEST_INGREDIENTS = "REQUEST_INGREDIENTS";
export const RECEIVED_INGREDIENTS = "RECEIVED_INGREDIENTS";
export const REQUEST_INGREDIENTS_FAILURE = "REQUEST_INGREDIENTS_FAILURE";

export const REQUEST_ORDERS = "REQUEST_ORDERS";
export const RECEIVED_ORDERS = "RECEIVED_ORDERS";
export const REQUEST_ORDERS_FAILURE = "REQUEST_ORDERS_FAILURE";
